language: objective-c
cache:
- bundler
before_install: bundle install
script: pod lib testing
notifications:
  slack:
    secure: LM3GodLDCvADu0UyiTRIvMsku6sLSTYwn/yDFbhnsDajdKMbI8R7d7RmuF2r7ZkA+0qNEPLD5zoHfvxCRTu/03MKXrQ3Rh4MIHc1rJTkzszZIPmdLJ+eEgD5urjvYyqXuzgJXji0aSjSlWy0aSady1OzBsBO880jJltt6s4qWws=
env:
  global:
    secure: EmChGpGvvQ++DduzeqBrLZNJjpm3mFPFdHw3K2m/opAWAzJYq10xq8SiU1wmZVGhkVAdZJoNe0NwWGWOvfWiOmWW/+0r0W8pBrwkRcI8c/wzUMMkgpJfVNTyUa2MWnBnVAZNB7bM+dVJ3gvqmUHCquapM+L9Z8+GP0zKBlDsVwo=
