reference: http://www.objc.io/issue-6/travis-ci.html
language: objective-c
cache: bundler
script:
- xctool test -workspace Example/contentful-management.objc.xcworkspace -scheme contentful-management.objc -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
