language: objective-c
cache: bundler
before_install: cd Example && pod install && cd ..
script: pod lib testing
notifications:
  slack:
    secure: QfCvAzriwr2CTqXoAwuQMIIaghWxa3X7VLXEY4HQ83HIfZRnUUMbTeDUfBKjcOsys8OwgOGxNlTESviqWHuek1yu23UvYTBBsMBwcJBGfMXRMvEyZb/GT5wOof9k7SbKGDDu4AkpPNwuY3zqsn3wEijBWk01b4ocOIbYsDMK/ic=
